export const envConfig = {
    SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    SPOTIFY_ACCESS_TOKEN: process.env.NEXT_PUBLIC_SPOTIFY_ACCESS_TOKEN
}